
#
# Cookbook Name:: QIIME
# Recipe:: default
#
# Copyright (c) 2016 The Authors, All Rights Reserved.

include_recipe 'apt'
include_recipe 'build-essential'
include_recipe 'r'

# ubuntu package dependencies for base qiime
# now need python-tk to prevent import _tkinter error.
# See eg. http://stackoverflow.com/questions/26702119/installing-tkinter-on-ubuntu-14-04
package %w(pkg-config libpng-dev libjpeg8-dev libfreetype6-dev python-tk) do
  action :install
end

python_runtime '2'

python_package 'numpy'

python_package 'qiime' do
  version node['QIIME']['version']
end

r_package 'ape'
r_package 'optparse'
r_package 'RColorBrewer'
r_package 'randomForest'
r_package 'vegan'
r_package 'RJSONIO'
r_package 'plyr'

# install biom R package from tar file

remote_file "#{Chef::Config[:file_cache_path]}/#{node['biom']['filename']}" do
  source node['biom']['url']
  action :create_if_missing
end

execute 'install_biom' do
  command "R CMD INSTALL #{Chef::Config[:file_cache_path]}/#{node['biom']['filename']}"
end

# other required packages

apt_package 'libxml2-dev'
apt_package 'libcurl4-openssl-dev'

script 'install_bioconductor_packages' do
  interpreter 'Rscript'
  code <<-SCRIPT
  source( 'http://bioconductor.org/biocLite.R' )
  biocLite(c("DESeq2"), dependencies = TRUE)
  biocLite("metagenomeSeq")
  biocLite("biomformat")
  q()
  SCRIPT
end

magic_shell_environment 'QIIME_VERSION' do
  value node['QIIME']['version']
end

# set the matplotlib backend to 'agg'
# otherwise png images cannot be generated by qiime
# when running ktichen verify
magic_shell_environment 'MPLBACKEND' do
  value 'agg'
end
