dist: xenial

before_install:
  - wget https://packages.chef.io/files/stable/chefdk/3.7.23/ubuntu/16.04/chefdk_3.7.23-1_amd64.deb
  - sudo dpkg -i chefdk_3.7.23-1_amd64.deb
  - chef --version

install: echo "skip bundle install"

branches:
  only:
  - master

env:
  matrix:
  - INSTANCE=default-ubuntu-1804

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef gem install kitchen-docker
- /opt/chefdk/bin/chef exec rake tests

script:
- /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

after_script:
- /opt/chefdk/embedded/bin/kitchen destroy ${INSTANCE}
