sudo: required
dist: trusty
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install: echo "skip bundle install"
branches:
  only:
  - master
services: docker
env:
  global:
  - RUBYOPT="-W0"
  - secure: UqcOQzhCShFLCNpbsZoO8uBLp9XUkAAEVIfcdCmp73Y8dF6B+EmeShtlYahCeC1tI2yKWCj2gFk6ZSn1hw8m59JJzd+kH6FU0yqsS5uhs4RrsY3crgSht4Z28UqzvnFXDrbUJ0M3NxdkWvKIAYLkHS82oAGXXcyuIhgnt75JMtK4y+7bNKt2KmPl3ueTUxT/rP6Fe8PeJdpIh2rHNbF4dsOct11VYHjtKaAahvHtEs+XxKgYWECO2OH1tfohXNvhk1Rz8iSHE+uoTNapL7ZKhRXpEisQp3vYGnAe2VpmF8C9ri9VfJSBMNnh8NusM0BTzgk7PkkxI2OcCCRmi5CG0vukUpO7mjbJFzGh89qH6+NzPdNHkDlp187ZA57dw0KpkDGAN1n9nQlpz37X7xvKPRWWXgRQy7p5uQnTkdK93bl6sWl3oSKARCeXYOjSOO+grzGMob7GibbmCqMKHJJmrdAMojdZi96/+HrrWdxl/F1AOIbjq0Uf0PvkH5kdGpso9G+DneHdUcJ7xluj5AyaoHuNRrWnwJNcxDa7GcNS167hcXT3fquSzE+1AoMpWOPbUDGiSqcV2RUfKyWlSFtcl2H5ooDB4Ek0YDzBbeXnUNLGYk3rVSXWBiJmlMVj2e/uK2NvREcWXZ/9JYuqJvQ/CC0QoDFzQZazW3LdxedWTIk=
  matrix:
  - CHEF_VERSION=current INSTANCE=default-ubuntu-1404
before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef gem install kitchen-docker
- "/opt/chefdk/bin/chef exec rake tests"
script:
- KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
notifications:
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: f5RvigWDLOqqoJkRN2i8vMVr4+bksqPiB8tYL60dpRRJvI9/a3KZS4SXbODWx+aOXXtTpY8JvECreYUo/PK24VQzGykGpK1uSU1nGe3Wh0K85BpyefRbx+eA3hWz/D4pxX1kNAObalPs2t9IzDGEWswYilTfwKppKHeH0OShWE3KVr+HY/iKcWKailZthjuKySwj+cPeyH601LtA+Z8+ySLtBo+sRtlZCLz2QjLI1OCqw2excpw/RFLxXW4ZNaHUeLVE9kynt4o6wOJmZtZTOTu1At9Ohvm+DNCSNfl/3Re30pkWJFNcItC1Y7iBykHVTcUxyL8M+HR3OaTuA1uvYxrZA5BfpCFCsfCBVktzcXWdQcX64cDVRWFXFlIUp+QUvpHOBIH4kcoQ3Wzt3RgyazZiaNC1TDw+s/LVV37+wjQPJnuFKIDEo1bXrsfsgECnhnp5+BU/xCErxwOWuVV1Yk2GN3xBik7OVXkMOr32UchYrndtHbt8dgrHWa5wdJCIQPYxyUoy2VZGMJm4WKBZeL4SBDmyWkhq4Rm8Ek3m/Z/XMz9gRMnTcm+em+a3ORqGGayyqvewKyBXBkd+TWBtCob3qOblfdIOAEqHwEL+/1plQ+IcgMlNrsOaWOGxESz/Qoe/rAvweInszNdpuS3I+QsmpeKvJJDQ2UgIedV//sw=
    on_failure: change
    on_success: change
  email:
    on_success: change
    on_failure: change
after_success:
- chmod +x trigger_dependent_build.sh
- "./trigger_dependent_build.sh EagleGenomics-cookbooks qiime_runnable private $TRAVIS_ACCESS_TOKEN"
