name 'QIIME'
maintainer 'EagleGenomics'
maintainer_email 'chef@eaglegenomics.com'
license 'Apache v2.0'
description 'Installs/Configures QIIME'
long_description 'Installs/Configures QIIME'
version '0.1.2'

source_url 'https://github.com/EagleGenomics-cookbooks/QIIME'
issues_url 'https://github.com/EagleGenomics-cookbooks/QIIME/issues'

depends 'build-essential'
depends 'magic_shell'
depends 'poise-python'
depends 'apt'
depends 'r'
